In [272]:
import pandas as pd
import numpy as np

print("Libraries imported successfully")

Libraries imported successfully

In [273]:
import sys
print(sys.executable)

/home/disni-maleesha/data-science-project/venv/bin/python

In [274]:
import os

os.listdir()

['venv',
 'FinTrust_Credit_Risk_Analysis.ipynb',
 '.ipynb_checkpoints',
 'default of credit card clients.csv']

In [275]:
import pandas as pd

df = pd.read_csv("default of credit card clients.csv")

# df.head(10)

In [276]:
df = pd.read_csv(
    "default of credit card clients.csv",
    header=1
)

df.head(10)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
5,6,50000,1,1,2,37,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
6,7,500000,1,1,2,29,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
7,8,100000,2,2,2,23,0,-1,-1,0,...,221,-159,567,380,601,0,581,1687,1542,0
8,9,140000,2,3,1,28,0,0,2,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0
9,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,13007,13912,0,0,0,13007,1122,0,0

In [277]:
df.shape

(30000, 25)

In [278]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_1                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

In [279]:
print(df.describe())

                 ID       LIMIT_BAL           SEX     EDUCATION      MARRIAGE  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000
mean   15000.500000   167484.322667      1.603733      1.853133      1.551867
std     8660.398374   129747.661567      0.489129      0.790349      0.521970
min        1.000000    10000.000000      1.000000      0.000000      0.000000
25%     7500.750000    50000.000000      1.000000      1.000000      1.000000
50%    15000.500000   140000.000000      2.000000      2.000000      2.000000
75%    22500.250000   240000.000000      2.000000      2.000000      2.000000
max    30000.000000  1000000.000000      2.000000      6.000000      3.000000

                AGE         PAY_1         PAY_2         PAY_3         PAY_4  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000
mean      35.485500     -0.016700     -0.133767     -0.166200     -0.220667
std        9.217904      1.123802      1.197186      1.196868      1.169139
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000
50%       34.000000      0.000000      0.000000      0.000000      0.000000
75%       41.000000      0.000000      0.000000      0.000000      0.000000
max       79.000000      8.000000      8.000000      8.000000      8.000000

       ...      BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000
mean   ...   43262.948967   40311.400967   38871.760400    5663.580500
std    ...   64332.856134   60797.155770   59554.107537   16563.280354
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000
25%    ...    2326.750000    1763.000000    1256.000000    1000.000000
50%    ...   19052.000000   18104.500000   17071.000000    2100.000000
75%    ...   54506.000000   50190.500000   49198.250000    5006.000000
max    ...  891586.000000  927171.000000  961664.000000  873552.000000

           PAY_AMT2      PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000
mean   5.921163e+03    5225.68150    4826.076867    4799.387633
std    2.304087e+04   17606.96147   15666.159744   15278.305679
min    0.000000e+00       0.00000       0.000000       0.000000
25%    8.330000e+02     390.00000     296.000000     252.500000
50%    2.009000e+03    1800.00000    1500.000000    1500.000000
75%    5.000000e+03    4505.00000    4013.250000    4031.500000
max    1.684259e+06  896040.00000  621000.000000  426529.000000

            PAY_AMT6  default payment next month
count   30000.000000                30000.000000
mean     5215.502567                    0.221200
std     17777.465775                    0.415062
min         0.000000                    0.000000
25%       117.750000                    0.000000
50%      1500.000000                    0.000000
75%      4000.000000                    0.000000
max    528666.000000                    1.000000

[8 rows x 25 columns]

In [280]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='str')

In [281]:
df.rename(columns={
    'ID': 'customer_id',
    'LIMIT_BAL': 'limit_balance',
    'SEX': 'sex',
    'EDUCATION': 'education',
    'MARRIAGE': 'marriage',
    'AGE': 'age',
    'PAY_1': 'pay_status_1',
    'PAY_2': 'pay_status_2',
    'PAY_3': 'pay_status_3',
    'PAY_4': 'pay_status_4',
    'PAY_5': 'pay_status_5',
    'PAY_6': 'pay_status_6',
    'BILL_AMT1': 'bill_amount_1',
    'BILL_AMT2': 'bill_amount_2',
    'BILL_AMT3': 'bill_amount_3',
    'BILL_AMT4': 'bill_amount_4',
    'BILL_AMT5': 'bill_amount_5',
    'BILL_AMT6': 'bill_amount_6',
    'PAY_AMT1': 'payment_amount_1',
    'PAY_AMT2': 'payment_amount_2',
    'PAY_AMT3': 'payment_amount_3',
    'PAY_AMT4': 'payment_amount_4',
    'PAY_AMT5': 'payment_amount_5',
    'PAY_AMT6': 'payment_amount_6',
    'default payment next month': 'default_next_month'
}, inplace=True)

In [282]:
df['sex'] = df['sex'].map({
    1: 'Male',
    2: 'Female'
})

In [283]:
df['sex'].value_counts(dropna=False)

sex
Female    18112
Male      11888
Name: count, dtype: int64

In [284]:
df['education'] = df['education'].map({
    1: 'Graduate School',
    2: 'University',
    3: 'High School',
    4: 'Others',
    5: 'Unknown',
    6: 'Unknown',
    0: 'Unknown'
})

In [285]:
df['education'].value_counts(dropna=False)

education
University         14030
Graduate School    10585
High School         4917
Unknown              345
Others               123
Name: count, dtype: int64

In [286]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,bill_amount_4,bill_amount_5,bill_amount_6,payment_amount_1,payment_amount_2,payment_amount_3,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month
0,1,20000,Female,University,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,Female,University,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,Female,University,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,Female,University,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,Male,University,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
5,6,50000,Male,Graduate School,2,37,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
6,7,500000,Male,Graduate School,2,29,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
7,8,100000,Female,University,2,23,0,-1,-1,0,...,221,-159,567,380,601,0,581,1687,1542,0
8,9,140000,Female,High School,1,28,0,0,2,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0
9,10,20000,Male,High School,2,35,-2,-2,-2,-2,...,0,13007,13912,0,0,0,13007,1122,0,0

In [287]:
df['marriage'] = df['marriage'].map({
    1: 'Married',
    2: 'Single',
    3: 'Others',
    0: 'Unknown'
})

In [288]:
df['marriage'].value_counts(dropna=False)

marriage
Single     15964
Married    13659
Others       323
Unknown       54
Name: count, dtype: int64

In [289]:
# Check duplicate rows
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows found: {duplicate_count}")

if duplicate_count > 0:
    df.drop_duplicates(inplace=True)
    print("--- Duplicate rows dropped successfully! ---")


# Create Age Group Feature
age_bins = [20, 30, 45, 60, 80]

age_labels = [
    'Young Adult (21-30)',
    'Middle-Aged (31-45)',
    'Senior-Aged (46-60)',
    'Elderly (61-80)'
]

df['age_group'] = pd.cut(
    df['age'],
    bins=age_bins,
    labels=age_labels
)
# Create Total Bill Amount Feature
bill_cols = [
    'bill_amount_1',
    'bill_amount_2',
    'bill_amount_3',
    'bill_amount_4',
    'bill_amount_5',
    'bill_amount_6'
]

df['total_bill_amount'] = df[bill_cols].sum(axis=1)


print("\n--- Feature Engineering Completed! ---")

print(df[['age', 'age_group']].head())

Number of duplicate rows found: 0

--- Feature Engineering Completed! ---
   age            age_group
0   24  Young Adult (21-30)
1   26  Young Adult (21-30)
2   34  Middle-Aged (31-45)
3   37  Middle-Aged (31-45)
4   57  Senior-Aged (46-60)

In [290]:
bill_cols = [
    'bill_amount_1',
    'bill_amount_2',
    'bill_amount_3',
    'bill_amount_4',
    'bill_amount_5',
    'bill_amount_6'
]

df['total_bill_amount'] = df[bill_cols].sum(axis=1)

print(df[['total_bill_amount']].head())

   total_bill_amount
0               7704
1              17077
2             101653
3             231334
4             109339

In [291]:
df['education'].value_counts(dropna=False)

education
University         14030
Graduate School    10585
High School         4917
Unknown              345
Others               123
Name: count, dtype: int64

In [292]:
df['education'].value_counts(dropna=False)

education
University         14030
Graduate School    10585
High School         4917
Unknown              345
Others               123
Name: count, dtype: int64

In [293]:
df['age'].describe()

count    30000.000000
mean        35.485500
std          9.217904
min         21.000000
25%         28.000000
50%         34.000000
75%         41.000000
max         79.000000
Name: age, dtype: float64

In [294]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,bill_amount_6,payment_amount_1,payment_amount_2,payment_amount_3,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,0,0,689,0,0,0,0,1,Young Adult (21-30),7704
1,2,120000,Female,University,Single,26,-1,2,0,0,...,3261,0,1000,1000,1000,0,2000,1,Young Adult (21-30),17077
2,3,90000,Female,University,Single,34,0,0,0,0,...,15549,1518,1500,1000,1000,1000,5000,0,Middle-Aged (31-45),101653
3,4,50000,Female,University,Married,37,0,0,0,0,...,29547,2000,2019,1200,1100,1069,1000,0,Middle-Aged (31-45),231334
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,19131,2000,36681,10000,9000,689,679,0,Senior-Aged (46-60),109339
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,20024,2500,1815,657,1000,1000,800,0,Middle-Aged (31-45),238114
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,473944,55000,40000,38000,20239,13750,13770,0,Young Adult (21-30),2724595
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,567,380,601,0,581,1687,1542,0,Young Adult (21-30),13486
8,9,140000,Female,High School,Married,28,0,0,2,0,...,3719,3329,0,432,1000,1000,1000,0,Young Adult (21-30),65212
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,13912,0,0,0,13007,1122,0,0,Middle-Aged (31-45),26919

In [295]:
df['pay_status_1'].value_counts().sort_index()

pay_status_1
-2     2759
-1     5686
 0    14737
 1     3688
 2     2667
 3      322
 4       76
 5       26
 6       11
 7        9
 8       19
Name: count, dtype: int64

In [296]:
for col in ['pay_status_1','pay_status_2','pay_status_3',
            'pay_status_4','pay_status_5','pay_status_6']:
    print("----", col, "----")
    print(df[col].value_counts().sort_index())
    print()

---- pay_status_1 ----
pay_status_1
-2     2759
-1     5686
 0    14737
 1     3688
 2     2667
 3      322
 4       76
 5       26
 6       11
 7        9
 8       19
Name: count, dtype: int64

---- pay_status_2 ----
pay_status_2
-2     3782
-1     6050
 0    15730
 1       28
 2     3927
 3      326
 4       99
 5       25
 6       12
 7       20
 8        1
Name: count, dtype: int64

---- pay_status_3 ----
pay_status_3
-2     4085
-1     5938
 0    15764
 1        4
 2     3819
 3      240
 4       76
 5       21
 6       23
 7       27
 8        3
Name: count, dtype: int64

---- pay_status_4 ----
pay_status_4
-2     4348
-1     5687
 0    16455
 1        2
 2     3159
 3      180
 4       69
 5       35
 6        5
 7       58
 8        2
Name: count, dtype: int64

---- pay_status_5 ----
pay_status_5
-2     4546
-1     5539
 0    16947
 2     2626
 3      178
 4       84
 5       17
 6        4
 7       58
 8        1
Name: count, dtype: int64

---- pay_status_6 ----
pay_status_6
-2     4895
-1     5740
 0    16286
 2     2766
 3      184
 4       49
 5       13
 6       19
 7       46
 8        2
Name: count, dtype: int64

In [297]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,bill_amount_6,payment_amount_1,payment_amount_2,payment_amount_3,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,0,0,689,0,0,0,0,1,Young Adult (21-30),7704
1,2,120000,Female,University,Single,26,-1,2,0,0,...,3261,0,1000,1000,1000,0,2000,1,Young Adult (21-30),17077
2,3,90000,Female,University,Single,34,0,0,0,0,...,15549,1518,1500,1000,1000,1000,5000,0,Middle-Aged (31-45),101653
3,4,50000,Female,University,Married,37,0,0,0,0,...,29547,2000,2019,1200,1100,1069,1000,0,Middle-Aged (31-45),231334
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,19131,2000,36681,10000,9000,689,679,0,Senior-Aged (46-60),109339
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,20024,2500,1815,657,1000,1000,800,0,Middle-Aged (31-45),238114
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,473944,55000,40000,38000,20239,13750,13770,0,Young Adult (21-30),2724595
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,567,380,601,0,581,1687,1542,0,Young Adult (21-30),13486
8,9,140000,Female,High School,Married,28,0,0,2,0,...,3719,3329,0,432,1000,1000,1000,0,Young Adult (21-30),65212
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,13912,0,0,0,13007,1122,0,0,Middle-Aged (31-45),26919

In [298]:
bill_columns = [
    'bill_amount_1',
    'bill_amount_2',
    'bill_amount_3',
    'bill_amount_4',
    'bill_amount_5',
    'bill_amount_6'
]

df[bill_columns].describe()

,bill_amount_1,bill_amount_2,bill_amount_3,bill_amount_4,bill_amount_5,bill_amount_6
count,30000.000000,30000.000000,3.000000e+04,30000.000000,30000.000000,30000.000000
mean,51223.330900,49179.075167,4.701315e+04,43262.948967,40311.400967,38871.760400
std,73635.860576,71173.768783,6.934939e+04,64332.856134,60797.155770,59554.107537
min,-165580.000000,-69777.000000,-1.572640e+05,-170000.000000,-81334.000000,-339603.000000
25%,3558.750000,2984.750000,2.666250e+03,2326.750000,1763.000000,1256.000000
50%,22381.500000,21200.000000,2.008850e+04,19052.000000,18104.500000,17071.000000
75%,67091.000000,64006.250000,6.016475e+04,54506.000000,50190.500000,49198.250000
max,964511.000000,983931.000000,1.664089e+06,891586.000000,927171.000000,961664.000000

In [299]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,bill_amount_6,payment_amount_1,payment_amount_2,payment_amount_3,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,0,0,689,0,0,0,0,1,Young Adult (21-30),7704
1,2,120000,Female,University,Single,26,-1,2,0,0,...,3261,0,1000,1000,1000,0,2000,1,Young Adult (21-30),17077
2,3,90000,Female,University,Single,34,0,0,0,0,...,15549,1518,1500,1000,1000,1000,5000,0,Middle-Aged (31-45),101653
3,4,50000,Female,University,Married,37,0,0,0,0,...,29547,2000,2019,1200,1100,1069,1000,0,Middle-Aged (31-45),231334
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,19131,2000,36681,10000,9000,689,679,0,Senior-Aged (46-60),109339
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,20024,2500,1815,657,1000,1000,800,0,Middle-Aged (31-45),238114
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,473944,55000,40000,38000,20239,13750,13770,0,Young Adult (21-30),2724595
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,567,380,601,0,581,1687,1542,0,Young Adult (21-30),13486
8,9,140000,Female,High School,Married,28,0,0,2,0,...,3719,3329,0,432,1000,1000,1000,0,Young Adult (21-30),65212
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,13912,0,0,0,13007,1122,0,0,Middle-Aged (31-45),26919

In [300]:
payment_columns = [
    'payment_amount_1',
    'payment_amount_2',
    'payment_amount_3',
    'payment_amount_4',
    'payment_amount_5',
    'payment_amount_6'
]

df[payment_columns].describe()

,payment_amount_1,payment_amount_2,payment_amount_3,payment_amount_4,payment_amount_5,payment_amount_6
count,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000
mean,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567
std,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775
min,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000
25%,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000
50%,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000
75%,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000
max,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000

In [301]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,bill_amount_6,payment_amount_1,payment_amount_2,payment_amount_3,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,0,0,689,0,0,0,0,1,Young Adult (21-30),7704
1,2,120000,Female,University,Single,26,-1,2,0,0,...,3261,0,1000,1000,1000,0,2000,1,Young Adult (21-30),17077
2,3,90000,Female,University,Single,34,0,0,0,0,...,15549,1518,1500,1000,1000,1000,5000,0,Middle-Aged (31-45),101653
3,4,50000,Female,University,Married,37,0,0,0,0,...,29547,2000,2019,1200,1100,1069,1000,0,Middle-Aged (31-45),231334
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,19131,2000,36681,10000,9000,689,679,0,Senior-Aged (46-60),109339
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,20024,2500,1815,657,1000,1000,800,0,Middle-Aged (31-45),238114
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,473944,55000,40000,38000,20239,13750,13770,0,Young Adult (21-30),2724595
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,567,380,601,0,581,1687,1542,0,Young Adult (21-30),13486
8,9,140000,Female,High School,Married,28,0,0,2,0,...,3719,3329,0,432,1000,1000,1000,0,Young Adult (21-30),65212
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,13912,0,0,0,13007,1122,0,0,Middle-Aged (31-45),26919

In [302]:
bill_columns = [
    'bill_amount_1',
    'bill_amount_2',
    'bill_amount_3',
    'bill_amount_4',
    'bill_amount_5',
    'bill_amount_6'
]

df['avg_bill_amount'] = df[bill_columns].mean(axis=1)

df[['avg_bill_amount']].head()

   avg_bill_amount
0      1284.000000
1      2846.166667
2     16942.166667
3     38555.666667
4     18223.166667

In [303]:
payment_columns = [
    'payment_amount_1',
    'payment_amount_2',
    'payment_amount_3',
    'payment_amount_4',
    'payment_amount_5',
    'payment_amount_6'
]

df['avg_payment_amount'] = df[payment_columns].mean(axis=1)

df[['avg_payment_amount']].head()

   avg_payment_amount
0          114.833333
1          833.333333
2         1836.333333
3         1398.000000
4         9841.500000

In [304]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,payment_amount_2,payment_amount_3,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount,avg_bill_amount,avg_payment_amount
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,689,0,0,0,0,1,Young Adult (21-30),7704,1284.000000,114.833333
1,2,120000,Female,University,Single,26,-1,2,0,0,...,1000,1000,1000,0,2000,1,Young Adult (21-30),17077,2846.166667,833.333333
2,3,90000,Female,University,Single,34,0,0,0,0,...,1500,1000,1000,1000,5000,0,Middle-Aged (31-45),101653,16942.166667,1836.333333
3,4,50000,Female,University,Married,37,0,0,0,0,...,2019,1200,1100,1069,1000,0,Middle-Aged (31-45),231334,38555.666667,1398.000000
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,36681,10000,9000,689,679,0,Senior-Aged (46-60),109339,18223.166667,9841.500000
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,1815,657,1000,1000,800,0,Middle-Aged (31-45),238114,39685.666667,1295.333333
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,40000,38000,20239,13750,13770,0,Young Adult (21-30),2724595,454099.166667,30126.500000
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,601,0,581,1687,1542,0,Young Adult (21-30),13486,2247.666667,798.500000
8,9,140000,Female,High School,Married,28,0,0,2,0,...,0,432,1000,1000,1000,0,Young Adult (21-30),65212,10868.666667,1126.833333
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,0,0,13007,1122,0,0,Middle-Aged (31-45),26919,4486.500000,2354.833333

In [305]:
df['payment_to_bill_ratio'] = (
    df['avg_payment_amount'] / df['avg_bill_amount']
)

df[['payment_to_bill_ratio']].head()

   payment_to_bill_ratio
0               0.089434
1               0.292791
2               0.108388
3               0.036259
4               0.540054

In [306]:
pay_columns = [
    'pay_status_1',
    'pay_status_2',
    'pay_status_3',
    'pay_status_4',
    'pay_status_5',
    'pay_status_6'
]

df['delayed_months'] = (df[pay_columns] > 0).sum(axis=1)

df[['delayed_months']].head()

   delayed_months
0               2
1               2
2               0
3               0
4               0

In [307]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount,avg_bill_amount,avg_payment_amount,payment_to_bill_ratio,delayed_months
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,0,0,0,1,Young Adult (21-30),7704,1284.000000,114.833333,0.089434,2
1,2,120000,Female,University,Single,26,-1,2,0,0,...,1000,0,2000,1,Young Adult (21-30),17077,2846.166667,833.333333,0.292791,2
2,3,90000,Female,University,Single,34,0,0,0,0,...,1000,1000,5000,0,Middle-Aged (31-45),101653,16942.166667,1836.333333,0.108388,0
3,4,50000,Female,University,Married,37,0,0,0,0,...,1100,1069,1000,0,Middle-Aged (31-45),231334,38555.666667,1398.000000,0.036259,0
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,9000,689,679,0,Senior-Aged (46-60),109339,18223.166667,9841.500000,0.540054,0
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,1000,1000,800,0,Middle-Aged (31-45),238114,39685.666667,1295.333333,0.032640,0
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,20239,13750,13770,0,Young Adult (21-30),2724595,454099.166667,30126.500000,0.066343,0
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,581,1687,1542,0,Young Adult (21-30),13486,2247.666667,798.500000,0.355257,0
8,9,140000,Female,High School,Married,28,0,0,2,0,...,1000,1000,1000,0,Young Adult (21-30),65212,10868.666667,1126.833333,0.103677,1
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,13007,1122,0,0,Middle-Aged (31-45),26919,4486.500000,2354.833333,0.524871,0

In [308]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount,avg_bill_amount,avg_payment_amount,payment_to_bill_ratio,delayed_months
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,0,0,0,1,Young Adult (21-30),7704,1284.000000,114.833333,0.089434,2
1,2,120000,Female,University,Single,26,-1,2,0,0,...,1000,0,2000,1,Young Adult (21-30),17077,2846.166667,833.333333,0.292791,2
2,3,90000,Female,University,Single,34,0,0,0,0,...,1000,1000,5000,0,Middle-Aged (31-45),101653,16942.166667,1836.333333,0.108388,0
3,4,50000,Female,University,Married,37,0,0,0,0,...,1100,1069,1000,0,Middle-Aged (31-45),231334,38555.666667,1398.000000,0.036259,0
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,9000,689,679,0,Senior-Aged (46-60),109339,18223.166667,9841.500000,0.540054,0
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,1000,1000,800,0,Middle-Aged (31-45),238114,39685.666667,1295.333333,0.032640,0
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,20239,13750,13770,0,Young Adult (21-30),2724595,454099.166667,30126.500000,0.066343,0
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,581,1687,1542,0,Young Adult (21-30),13486,2247.666667,798.500000,0.355257,0
8,9,140000,Female,High School,Married,28,0,0,2,0,...,1000,1000,1000,0,Young Adult (21-30),65212,10868.666667,1126.833333,0.103677,1
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,13007,1122,0,0,Middle-Aged (31-45),26919,4486.500000,2354.833333,0.524871,0

In [309]:
# df['recent_balance_trend'] = (
#     df[['bill_amount_4','bill_amount_5','bill_amount_6']].mean(axis=1)
#     -
#     df[['bill_amount_1','bill_amount_2','bill_amount_3']].mean(axis=1)
# )

# df[['recent_balance_trend']].head()

In [310]:
df.head(10)

,customer_id,limit_balance,sex,education,marriage,age,pay_status_1,pay_status_2,pay_status_3,pay_status_4,...,payment_amount_4,payment_amount_5,payment_amount_6,default_next_month,age_group,total_bill_amount,avg_bill_amount,avg_payment_amount,payment_to_bill_ratio,delayed_months
0,1,20000,Female,University,Married,24,2,2,-1,-1,...,0,0,0,1,Young Adult (21-30),7704,1284.000000,114.833333,0.089434,2
1,2,120000,Female,University,Single,26,-1,2,0,0,...,1000,0,2000,1,Young Adult (21-30),17077,2846.166667,833.333333,0.292791,2
2,3,90000,Female,University,Single,34,0,0,0,0,...,1000,1000,5000,0,Middle-Aged (31-45),101653,16942.166667,1836.333333,0.108388,0
3,4,50000,Female,University,Married,37,0,0,0,0,...,1100,1069,1000,0,Middle-Aged (31-45),231334,38555.666667,1398.000000,0.036259,0
4,5,50000,Male,University,Married,57,-1,0,-1,0,...,9000,689,679,0,Senior-Aged (46-60),109339,18223.166667,9841.500000,0.540054,0
5,6,50000,Male,Graduate School,Single,37,0,0,0,0,...,1000,1000,800,0,Middle-Aged (31-45),238114,39685.666667,1295.333333,0.032640,0
6,7,500000,Male,Graduate School,Single,29,0,0,0,0,...,20239,13750,13770,0,Young Adult (21-30),2724595,454099.166667,30126.500000,0.066343,0
7,8,100000,Female,University,Single,23,0,-1,-1,0,...,581,1687,1542,0,Young Adult (21-30),13486,2247.666667,798.500000,0.355257,0
8,9,140000,Female,High School,Married,28,0,0,2,0,...,1000,1000,1000,0,Young Adult (21-30),65212,10868.666667,1126.833333,0.103677,1
9,10,20000,Male,High School,Single,35,-2,-2,-2,-2,...,13007,1122,0,0,Middle-Aged (31-45),26919,4486.500000,2354.833333,0.524871,0

In [311]:
df.to_csv("cleaned_credit_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!